version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: versioned_notes_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Run Rails app in Docker as well
  # Uncomment to run the full stack in Docker
  # web:
  #   build: .
  #   command: bundle exec rails server -b 0.0.0.0
  #   volumes:
  #     - .:/rails
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/versioned_notes_development
  #     RAILS_ENV: development

volumes:
  postgres_data:
